const data = {
    products: [
        {
            name: 'Nike Slim Shirt',
            slug: 'Nike-Slim-Shirt',
            category: 'Shirt',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Adidas Slim Shirt',
            slug: 'Adidas-Slim-Shirt',
            category: 'Shirt',
            image: '/images/p2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nike Fit Pant',
            slug: 'Nike-fit-Pant',
            category: 'Shirt',
            image: '/images/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Adidas Fit Pant',
            slug: 'Adidas-Fit-Pant',
            category: 'Shirt',
            image: '/images/p4.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
    ],
};
export default data;